import { RuleDetails } from "../contracts";

export const rules: RuleDetails[] = [
  {
    id: 1,
    name: "חוק הצניעות",
    initialInfo: "מעלה את המודעות לצניעות על ידי הפרדה בין נשים לגברים במרחב הציבורי",
    summaryInfo: "החוק מייצר הפרדה בין גברים לנשים לטובת המגזר החרדי. הוא פוגע בחופש התנועה של הנשים מכל המגזרים האחרים.",
    impact: { "orthodox-man": 1, "orthodox-woman": 1, "religious-woman":-1, "secular-woman":-1, "arab-woman":-1 },
    apply: { type: "Woman-Transparent", args: [{impact: { "orthodox-man": 1, "orthodox-woman": 1, "religious-woman":-1, "secular-woman":-1, "arab-woman":-1  }}] },
    isDelayed: true,
  },
  {
    id: 2,
    name: "חוק תורתם אמונתם",
    initialInfo: `פוטר את החרדים מגיוס לצה"ל כדי להעמיק את לימודי התורה`,
    summaryInfo: "החוק מפיל את נטל השירות הצבאי על חלק מהאוכלוסיה. הוא טוב לחרדים, פוגע במגזרים חילוניים והציוני הדתי ולא משפיע על המגזר הערבי שפטור מגיוס.",
    impact: { orthodox: 2, religious: -1, secular: -1, },
  },
  {
    id: 3,
    name: "חוק סמכויות בתי הדין הרבניים",
    initialInfo: `מרחיב את סמכויות בתי הדין הרבניים כך שישפטו בכל תחומי החיים בהתאם לחוקי ההלכה`,
    summaryInfo: "השיפוט לפי חוקי ההלכה נוטה לפסוק לטובת גברים. הוא פוגע בנשים מכל המגזרים, ואינו משפיע על המגזר הערבי הנשפט בבתי הדין השרעיים.",
    impact: { "orthodox-man": 1, "religious-man":1, "secular-man":1, "orthodox-woman": -1, "religious-woman":-1, "secular-woman":-1, "orthodox-lgbt": -1, "religious-lgbt":-1, "secular-lgbt":-1},
  },
  {
    id: 4,
    name: "חוק השבת",
    initialInfo: `שומר על קדושת השבת על ידי איסור על יהודים לעשות עבודות ציבוריות בשבת`,
    summaryInfo: "החוק מונע תעסוקה של המגזר החילוני. הוא טוב למגזר הערבי שיכול לעבוד בשבת ופוגע במגזר החילוני.",
    impact: { arab: 2, orthodox:1, secular:-1},
  },
  {
    id: 5,
    name: "חוק המפלגות היהודיות",
    initialInfo: `שומר על אופיה היהודי של הכנסת על ידי איסור על מפלגות איסלאמיות לרוץ בבחירות`,
    summaryInfo: "החוק פוגע במגזר הערבי שאין לו נציגות בכנסת.",
    impact: { arab: -1, orthodox:1, secular:1, religious:1},
  },
  {
    id: 6,
    name: "חוק האיזוק האלקטרוני",
    initialInfo: `מגן על אנשים בסיכון על ידי ענידת אזיק אלקטרוני על אנשים אלימים`,
    summaryInfo: "החוק מסייע במיגור האלימות נגד נשים. הוא טוב לנשים מכל המגזרים.",
    impact: { "-woman": 3, "-man":1, "-lgbt":1},
  },
  {
    id: 7,
    name: "חוק בחירת השירות",
    initialInfo: `מאפשר לאנשים לסרב לתת שירות לאחרים על סמך נטייה דתית או מינית או אחרת`,
    summaryInfo: "החוק מאפשר אפלייה של כל מגזר כנגד כל מגזר. הוא פוגע בכולם.",
    impact: { all: -1},
  },
  {
    id: 8,
    name: "חוק המילגות",
    initialInfo: `מעניק מילגות ליוצאי צבא`,
    summaryInfo: "החוק נותן יתרון לכל מי שעשה שירות צבאי. הוא טוב למגזר החילוני והציוני דתי.",
    impact: { arab: -1, orthodox:-1, secular:1, religious:1},
  },
  {
    id: 9,
    name: "חוק התחבורה הציבורית",
    initialInfo: `מאפשר נסיעה ציבורית בשבת`,
    summaryInfo: "החוק מאפשר תנועה בשבת. הוא טוב לחילונים וערבים ופוגע ברגשות המגזר החרדי.",
    impact: { arab: 2, orthodox:-1, secular:2 },
  },
  {
    id: 10,
    name: "חוק הצבא היהודי",
    initialInfo: `נותן צביון יהודי לצבא על ידי הפרדה של שירות הבנים משירות הבנות`,
    summaryInfo: "החוק מקל על שומרי מצוות בעת השירות הצבאי, אך פוגע בשיוויון המגדרי. הוא טוב למגדר הציוני דתי ופוגע במגדר החילוני.",
    impact: { "orthodox-man": 1, "religious-man":1, "secular-man":-1, "secular-woman": -1 },
  },
  {
    id: 11,
    name: "חוק הורות נכונה",
    initialInfo: `לאפשר רישום הורות רק לגבר ואישה ולא לזוגות מאותו מין `,
    summaryInfo: `החוק קובע זהות משפחתית מסוג אחד בלבד. הוא טוב למגזר החרדי ופוגע במגדר הלהט"בי בכל המגזרים.`,
    impact: { "orthodox-man": 1, "orthodox-woman":1, "-lgbt": -2 },
  },
  {
    id: 12,
    name: "חוק הורות מורחב",
    initialInfo: `מאפשר לזוגות מאותו מין להביא ילדים לעולם מפונדקאית `,
    summaryInfo: `החוק מכיר במשפחות חד מיניות ומשווה את זכויותיהם למשפחות רגילות. הוא טוב למגדר הלהט"בי ופוגע בציבור החרדי.`,
    impact: { "orthodox-man": -1, "orthodox-woman":-1, "-lgbt": 3 },
  },
  {
    id: 13,
    name: "חוק ההפלות",
    initialInfo: `מאפשר הפלות רק עם מניע המוגדר בחוק`,
    summaryInfo: `החוק מצמצם הפלות המיותרות אבל מונע מהאישה שליטה על גופה. החוק טוב למגזר החרדי ופוגע בנשים מכל המגזרים וגם בגברים שיגדלו ילד לא רצוי.`,
    impact: { "orthodox-man": 1, "orthodox-lgbt":1, "-woman": -3,  "arab-man": -1,  "religious-man": -1 },
  },
  {
    id: 14,
    name: "חוק בריאות הציבור",
    initialInfo: `מעודד אורח חיים בריא על ידי הטלת מס על משקאות ממותקים`,
    summaryInfo: `החוק מוריד את צריכת משקאות עתירי סוכר. הוא תורם לבריאות כל המגזרים ופוגע כלכלית במגזר החרדי שצורך הרבה שתייה ממותקת.`,
    impact: { arab: 1, orthodox:-1, secular:1, religious:1},
  },
  {
    id: 15,
    name: "חוק הגנת הסביבה",
    initialInfo: `מעודד שמירה על הסביבה על ידי הטלת מס על כלים חד פעמיים`,
    summaryInfo: `החוק מעודד שמירה על הסביבה. הוא טוב לכולם ופוגע במגזר החרדי בשל הרגלי הצריכה הכוללים הרבה כלים חד פעמיים.`,
    impact: { arab: 1, orthodox:-1, secular:1, religious:1},
  },
  {
    id: 16,
    name: "חוק האלכוהול",
    initialInfo: `מתחשב במגזר המוסלמי על ידי איסור מכירה של אלכוהול במהלך חודש הרמאדן`,
    summaryInfo: `החוק טוב למגזר הערבי ופוגע בכל יתר המגזרים.`,
    impact: { arab: 1, orthodox:-1, secular:-1, religious:-1},
  },
  {
    id: 17,
    name: "חוק החמץ",
    initialInfo: `שומר על צביון יהודי של המדינה על ידי איסור על שימוש בחמץ במרחב הציבורי במהלך פסח`,
    summaryInfo: `החוק טוב למגזר החרדי ופוגע בכל יתר המגזרים.`,
    impact: { arab: -1, orthodox:1, secular:-1, religious:1},
  },
  {
    id: 18,
    name: "חוק איחוד הרשויות השופטות",
    initialInfo: `שומר על שיוויון בפני החוק על ידי מיזוג בתי הדין הרבניים לתוך האזרחיים ומאפשר שיפוט רק לפי החוק הישראלי`,
    summaryInfo: `העברת סמכויות השיפוט לבתי הדין האזרחיים יפגע בגברים חרדים ודתיים בגלל העדפתם להישפט בהתאם לחוקי ההלכה.`,
    impact: {"orthodox-man":-2, "religious-man":-2, secular:2, "orthodox-woman":1, "religious-woman":1, "orthodox-lgbt":1, "religious-lgbt":1},
  },
  {
    id: 19,
    name: "חוק מדינת כל אזרחיה",
    initialInfo: `מבסס את הדמוקרטיה הישראלית על ידי ביטול חוק הלאום המגדיר את ישראל כמדינת היהודים בלבד`,
    summaryInfo: `חוק הלאום שמגדיר את ישראל כמדינת היהודים בלבד מבוטל. הביטול פוגע במגזר החרדי הרוצה מדינה יהודית ותורמת למגזר הערבי.`,
    impact: {orthodox:-1,  arab:3 },
  },
  {
    id: 20,
    name: "חוק האם הישראלית",
    initialInfo: `מעודד נשים להישאר בבית על ידי הארכת חופשת הלידה לשנתיים`,
    summaryInfo: `החוק נותן מימון לחופשת לידה ארוכה לנשים. הוא טוב לנשים בכל המגזרים.`,
    impact: {"-woman":2 },
  },
  {
    id: 21,
    name: "חוק עידוד העבודה לנשים",
    initialInfo: `מעודד נשים לצאת לעבודה על ידי קיצוץ חופשת הלידה לחודש וחצי`,
    summaryInfo: `החוק מצמצם את חופשת הלידה ופוגע בנשים.`,
    impact: {"-woman":-1 },
  },
  {
    id: 22,
    name: "חוק חינוך חינם",
    initialInfo: `מעודד נשים לצאת לעבודה על ידי תשלום על מסגרות חינוך לילדים החל מגיל שלושה חודשים`,
    summaryInfo: `החוק מעודד נשים לצאת לעבודה. הוא טוב לכולם אך במיוחד לנשים.`,
    impact: {"-woman":2, "-man":1, "-lgbt":1 },
  },
  {
    id: 23,
    name: "חוק תקשורת",
    initialInfo: `מצמצם את הוצאות הממשלה על ידי סגירת ערוצי תקשורת מיותרים`,
    summaryInfo: `החוק פוגע בחופש הביטוי של כל המגזרים.`,
    impact: { muted: 1 },
    apply: { type: "Muted" },
    isDelayed: true,
  },
  {
    id: 24,
    name: "חוק השיוויון",
    initialInfo: `מבסס את השיוויון בפני החוק של כל המגזרים והמגדרים`,
    summaryInfo: `החוק מעגן את חוק יסוד השיוויון כחוק יסוד. הוא טוב לכולם.`,
    impact: { all: 0 },
    apply: { type: "Average-Location" },
    isDelayed: true,
  },
  {
    id: 25,
    name: "הצבעת אי אמון בממשלה",
    initialInfo: `להחליף את הממשלה`,
    summaryInfo: `ההצעה מבטלת את כל החוקים שאושרו עד עכשיו. כל המגזרים נעים במהירות אחידה.`,
    impact: { all: 0 },
    apply: { type: "Reset" },
    isDelayed: true,
  },
  {
    id: 26,
    name: "חוק ביטול השבות",
    initialInfo: `מונע התפוצצות אוכלוסין במדינה`,
    summaryInfo: `החוק מונע עלייה לארץ. הוא טוב למגזר הערבי ופוגע בכל שאר המגזרים.`,
    impact: { arab: 1, orthodox:-1, secular:-1, religious:-1},
  },
  {
    id: 27,
    name: "חוק למניעת התעללות",
    initialInfo: `מעמיק את מעורבות הציבור במאבק כנגד התעללות`,
    summaryInfo: `החוק מעודד אנשים לדווח על התעללות בחסרי ישע. הוא טוב לכולם.`,
    impact: { all:1},
  },
  {
    id: 28,
    name: "חוק מניעת הסחיטה",
    initialInfo: `נלחם בפשיעה על ידי הרחבה של הגדרת הסחיטה`,
    summaryInfo: `החוק מאפשר להעמיד לדין יותר סחטנים ומוריד את רמת הפשיעה. הוא טוב לכולם.`,
    impact: { all:1},
  },
  {
    id: 29,
    name: "חוק ההנגשה",
    initialInfo: `מנגיש את שירותי הממשלה על ידי שימוש בשפות נוספות`,
    summaryInfo: `החוק מקל על הציבור לקבל את הטיפול הנדרש במשרדי הממשלה. הוא טוב לכולם.`,
    impact: { all:1},
  },
  {
    id: 30,
    name: "חוק הפנסיה",
    initialInfo: `מאפשר לפנסיונרים לקבל קצבה מלאה ללא תלות בקבלת קצבה אחרת`,
    summaryInfo: `החוק מאפשר לפנסיונרים לחיות ברווחה. הוא טוב לכולם.`,
    impact: { all:1},
  },
  {
    id: 31,
    name: "חוק החינוך המיוחד",
    initialInfo: `מאפשר לילדים במוסדות החינוך המיוחד ללמוד בשפה שלהם`,
    summaryInfo: `החוק מאפשר לילדים בחינוך מיוחד למצות את הפוטנציאל שלהם. הוא טוב לכולם.`,
    impact: { all:1},
  },
  {
    id: 32,
    name: "חוק לימודי ליבה",
    initialInfo: `מקדם את כלכלת המדינה על ידי לימודי ליבה`,
    summaryInfo: `החוק מרחיב את הידע וההשכלה במדינה ומאפשר פריחה כלכלית. הוא טוב לכל המגזרים מלבד החרדים שלא יקבלו תקצוב למוסדות שאין בהם לימודי ליבה.`,
    impact: { arab: 1, orthodox:-1, secular:1, religious:1},
  },
  {
    id: 33,
    name: "חוק הייצוג ההולם",
    initialInfo: `מקדם את התרבות בישראל על ידי ייצוג של חילוניים במשרד התרבות`,
    summaryInfo: `החוק מאפשר פריחה תרבותית חילונית. הוא טוב למגזר החילוני ופוגע בכל שאר המגזרים.`,
    impact: { arab: -1, orthodox:-1, secular:1, religious:-1},
  },
  {
    id: 34,
    name: "חוק העונשין לפגיעות מיניות",
    initialInfo: `נלחם בפגיעות המיניות על ידי הארכת התקופה המותרת להגשת תלונה ל-25 שנים`,
    summaryInfo: `החוק מאפשר לקורבן התקיפה למצות את הדין עם התוקף גם אם חלפו שנים רבות. הוא טוב לנשים מכל המגזרים.`,
    impact: { "-woman": 1},
  },
  {
    id: 35,
    name: "הרחבת חוק השבות",
    initialInfo: `מעניק למדינה צביון יהודי`,
    summaryInfo: `החוק מעודד עלייה של יהודים ושומר על הצביון היהודי של המדינה. הוא טוב לכל המגזרים מלבד המגזר הערבי.`,
    impact: { arab: -1, orthodox:1, secular:1, religious:1},
  },

  
];

export const allCharacterTypes = [
  {
    name: "orthodox-man",
    translation: "חרדי",
  },
  {
    name: "orthodox-woman",
    translation: "חרדית",
  },
  {
    name: "orthodox-lgbt",
    translation: "להט\"ב חרד",
  },
  {
    name: "arab-man",
    translation: "ערבי",
  },
  {
    name: "arab-woman",
    translation: "ערביה",
  },
  {
    name: "arab-lgbt",
    translation: "להט\"ב ערבי",
  },
  {
    name: "secular-man",
    translation: "חילוני",
  },
  {
    name: "secular-woman",
    translation: "חילונית",
  },
  {
    name: "secular-lgbt",
    translation: "להט\"ב חילוני",
  },
  {
    name: "religious-man",
    translation: "דתי ציוני",
  },
  {
    name: "religious-woman",
    translation: "דתייה ציונית",
  },
  {
    name: "religious-lgbt",
    translation: "להט\"ב דתי ציוני",
  },
];
